[project]
site_name = "fdl — Frozen DuckLake CLI"
site_description = "Frozen DuckLake CLI"
site_url = "https://fdl.flo8s.com/"
repo_url = "https://github.com/flo8s/fdl"
repo_name = "flo8s/fdl"

[project.theme]
features = [
    "navigation.instant",
    "navigation.instant.progress",
    "navigation.sections",
    "navigation.expand",
    "navigation.top",
    "navigation.footer",
    "content.code.copy",
    "content.code.annotate",
    "search.suggest",
    "search.highlight",
    "toc.follow",
]

[project.theme.icon]
logo = "material/snowflake"
repo = "fontawesome/brands/github"

[[project.theme.palette]]
scheme = "default"
primary = "deep purple"
accent = "deep purple"
toggle = { icon = "material/brightness-7", name = "Switch to dark mode" }

[[project.theme.palette]]
scheme = "slate"
primary = "deep purple"
accent = "deep purple"
toggle = { icon = "material/brightness-4", name = "Switch to light mode" }

[project.plugins.mkdocstrings.handlers.python]
paths = ["src"]

[project.plugins.mkdocstrings.handlers.python.options]
show_source = false
show_root_heading = true
show_root_full_path = true
show_signature_annotations = true
separate_signature = true
heading_level = 2
docstring_section_style = "spacy"

[project.markdown_extensions."pymdownx.highlight"]
anchor_linenums = true
pygments_lang_class = true

[project.markdown_extensions."pymdownx.superfences"]

[project.markdown_extensions."pymdownx.snippets"]
